import elf, munchkins, levers, lollipops, yeeters, pits
lever0, lever1, lever2, lever3, lever4 = levers.get()
elf.moveLeft(2)
lever4.pull("A String")
elf.moveUp (2)
lever3.pull(True)
elf.moveUp (2)
lever2.pull(1)
elf.moveUp (2)
lever1.pull([''])
elf.moveUp (2)
lever0.pull({})
elf.moveUp(20)
